default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: xplan_development

test:
  <<: *default
  database: xplan_test

production:
  <<: *default
  database: xplan_production
  username: xplan
  password: <%= ENV['XLPLAN_DATABASE_PASSWORD'] %>
